name: Build and Deploy Static Site

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 10.14.0

            - name: Install dependencies
              run: |
                  pnpm install --frozen-lockfile || pnpm add -D htmlhint stylelint stylelint-config-standard

            - name: Lint HTML
              run: pnpm exec htmlhint index.html

            - name: Lint CSS
              run: |
                  echo "/* dummy */" > styles.css
                  pnpm exec stylelint styles.css

            - name: Run basic tests
              run: ./test.sh

    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: .
